"use strict";
exports.__esModule = true;
exports.apiroute = void 0;
var express = require("express");
var api_controller = require('../controllers/apicontroller');
var route = express.Router();
exports.apiroute = route;
route.get('/getcount/articles', api_controller.getCountArticles);
route.get('/getcount/sub', api_controller.getCountSub);
route.get('/getcount/visitors', api_controller.getCountVisitors);
