"use strict";
exports.__esModule = true;
exports.blogroute = void 0;
var express = require("express");
var blog_controller = require('../controllers/blogcontroller');
var route = express.Router();
exports.blogroute = route;
route.get('/git', blog_controller.getGit);
route.get('/git/:pr/:text', blog_controller.getGitContents);
route.get('/researches', blog_controller.getArticleMain);
route.get('/researches/:id', blog_controller.getArticles);
