"use strict";
exports.__esModule = true;
exports.routes = void 0;
var express_1 = require("express");
var mainroute_1 = require("./mainroute");
var blogroute_1 = require("./blogroute");
var loginroute_1 = require("./loginroute");
var adminroute_1 = require("./adminroute");
var logoutroute_1 = require("./logoutroute");
var apiroute_1 = require("./apiroute");
var routes = express_1.Router();
exports.routes = routes;
routes.use('/', mainroute_1.mainroute);
routes.use('/blog', blogroute_1.blogroute);
routes.use('/login', loginroute_1.loginroute);
routes.use('/admin', adminroute_1.adminroute);
routes.use('/logout', logoutroute_1.logoutroute);
routes.use('/api', apiroute_1.apiroute);
